# Generated by Django 5.0.2 on 2024-08-02 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_conversationmessage_is_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ('-created_at',)},
        ),
    ]
