# Generated by Django 5.0.2 on 2024-08-02 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0003_alter_conversation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversationmessage',
            options={'ordering': ('-created_at',)},
        ),
    ]
